adaptive_hockey_federation/adaptive_hockey_federation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

adaptive_hockey_federation/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("users.urls", namespace="users")),
    path("", include("competitions.urls", namespace="competitions")),
    path("", include("analytics.urls", namespace="analytics")),
    path("", include("unloads.urls", namespace="unloads")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.not_found"
handler403 = "core.views.forbidden"
handler500 = "core.views.internal_server_error"

adaptive_hockey_federation/main/urls.py
from django.urls import include, path
from main.controllers import (
    ajax,
    main_views,
    player_views,
    staff_views,
    team_views,
)

app_name = "main"

main_urlpatterns = [
    path("", main_views.MainView.as_view(), name="main"),
]

players_urlpatterns = [
    path("", player_views.PlayersListView.as_view(), name="players"),
    path(
        "create/",
        player_views.PlayerIDCreateView.as_view(),
        name="player_create",
    ),
    path(
        "<int:pk>/",
        player_views.PlayerIdView.as_view(),
        name="player_id",
    ),
    path(
        "<int:pk>/edit/",
        player_views.PlayerIDEditView.as_view(),
        name="player_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        player_views.PlayerIDDeleteView.as_view(),
        name="player_id_delete",
    ),
    path(
        "deleted/",
        player_views.player_id_deleted,
        name="player_id_deleted",
    ),
]

teams_urlpatterns = [
    path("", team_views.TeamListView.as_view(), name="teams"),
    path(
        "create/",
        team_views.CreateTeamView.as_view(),
        name="team_create",
    ),
    path(
        "<int:team_id>/",
        team_views.TeamIdView.as_view(),
        name="teams_id",
    ),
    path(
        "<int:team_id>/edit/",
        team_views.UpdateTeamView.as_view(),
        name="team_update",
    ),
    path(
        "<int:team_id>/delete/",
        team_views.DeleteTeamView.as_view(),
        name="team_delete",
    ),
    path(
        "<int:team_id>/fire_staff/<int:staff_team_member_id>/",
        team_views.FireStaffFromTeam.as_view(),
        name="fire_staff_from_team",
    ),
]

staffs_urlpatterns = [
    path(
        "",
        staff_views.StaffMemberListView.as_view(),
        name="staffs",
    ),
    path(
        "create/",
        staff_views.StaffMemberIdCreateView.as_view(),
        name="staff_create",
    ),
    path(
        "<int:pk>/",
        staff_views.StaffMemberIdView.as_view(),
        name="staff_id",
    ),
    path(
        "<int:pk>/edit/",
        staff_views.StaffMemberIdEditView.as_view(),
        name="staff_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        staff_views.StaffMemberIdDeleteView.as_view(),
        name="staff_id_delete",
    ),
    path(
        "<int:pk>/<slug:position>/team/create/",
        staff_views.StaffMemberIdTeamCreateView.as_view(),
        name="staff_id_team_create",
    ),
    path(
        "<int:pk>/<slug:position>/team/edit/",
        staff_views.StaffMemberIDTeamEditView.as_view(),
        name="staff_id_team_edit",
    ),
    path(
        "<int:pk>/<slug:position>/team/delete/",
        staff_views.StaffMemberIdTeamDeleteView.as_view(),
        name="staff_id_team_delete",
    ),
]

ajax_urlpatterns = [
    path(
        "load-discipline-levels/",
        ajax.load_discipline_levels,
        name="ajax_load_discipline_levels",
    ),
    path(
        "filter-discipline-search/",
        ajax.filter_discipline_search,
        name="ajax_filter_discipline_search",
    ),
]

urlpatterns = [
    path("", include(main_urlpatterns)),
    path("players/", include(players_urlpatterns)),
    path("teams/", include(teams_urlpatterns)),
    path("staffs/", include(staffs_urlpatterns)),
    path("ajax/", include(ajax_urlpatterns)),
]

adaptive_hockey_federation/users/urls.py
from django.urls import include, path
from users.views import (
    CreateUserView,
    DeleteUserView,
    PasswordSetView,
    UpdateUserView,
    UsersListView,
)

app_name = "users"

users_urlpatterns = [
    path(
        "",
        UsersListView.as_view(),
        name="users",
    ),
    path(
        "create/",
        CreateUserView.as_view(),
        name="user_create",
    ),
    path(
        "<int:pk>/edit/",
        UpdateUserView.as_view(),
        name="user_update",
    ),
    path(
        "<int:pk>/delete/",
        DeleteUserView.as_view(),
        name="user_delete",
    ),
    path(
        "set_password/<uidb64>/<token>/",
        PasswordSetView.as_view(),
        name="password_set",
    ),
]

urlpatterns = [
    path("users/", include(users_urlpatterns)),
]

adaptive_hockey_federation/users/models.py
from typing import Iterable

from core.constants import GROUPS_BY_ROLE, ROLES_CHOICES, Role, UserConstans
from core.validators import fio_validator
from django.contrib.auth.models import (
    AbstractBaseUser,
    Group,
    PermissionsMixin,
)
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.validators import EmailValidator
from django.db import models
from django.http import Http404
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.validators import validate_international_phonenumber
from users.managers import CustomUserManager
from users.validators import zone_code_without_seven_hundred


class User(AbstractBaseUser, PermissionsMixin):
    """
    Кастомная модель пользователя.

    1. Поле 'username' исключено
    2. Идентификатором является поле с адресом электронной почты.
    """

    first_name = models.CharField(
        max_length=UserConstans.NAME_MAX_LENGTH,
        verbose_name=_("Имя"),
        help_text=_("Имя"),
        validators=[fio_validator()],
    )
    last_name = models.CharField(
        max_length=UserConstans.NAME_MAX_LENGTH,
        verbose_name=_("Фамилия"),
        help_text=_("Фамилия"),
        validators=[fio_validator()],
    )
    patronymic = models.CharField(
        blank=True,
        max_length=UserConstans.NAME_MAX_LENGTH,
        verbose_name=_("Отчество"),
        help_text=_("Отчество"),
        validators=[fio_validator()],
    )
    role = models.CharField(
        choices=ROLES_CHOICES,
        default=Role.AGENT,
        max_length=max(len(role) for role, _ in ROLES_CHOICES),
        verbose_name=_("Роль"),
        help_text=_("Уровень прав доступа"),
    )
    email = models.EmailField(
        max_length=UserConstans.EMAIL_MAX_LENGTH,
        unique=True,
        validators=(
            EmailValidator(
                message="Используйте корректный адрес электронной почты. "
                "Адрес должен быть не длиннее 150 символов. "
                "Допускается использование латинских букв, "
                "цифр и символов @/./+/-/_",
            ),
        ),
        verbose_name=_("Электронная почта"),
        help_text=_("Электронная почта"),
    )
    phone = PhoneNumberField(
        blank=True,
        validators=[
            validate_international_phonenumber,
            zone_code_without_seven_hundred,
        ],
        verbose_name=_("Актуальный номер телефона"),
        help_text=_("Номер телефона, допустимый формат - +7 ХХХ ХХХ ХХ ХХ"),
    )
    date_joined = models.DateTimeField(
        default=timezone.now,
        verbose_name=_("Дата регистрации"),
    )
    is_staff = models.BooleanField(
        default=False,
        verbose_name=_("Статус администратора."),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Показывает статус он-лайн."),
    )

    objects = CustomUserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "role"]

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")
        ordering = ("last_name",)
        permissions = [
            ("list_view_user", "Can view list of Пользователь"),
        ]

    def clean(self):
        """Метод валидации модели."""
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def __str__(self):
        """Использует метод get_initials() для строкового представления."""
        return self.get_initials()

    def get_initials(self) -> str:
        """
        Возвращает фамилию и инициалы пользователя.

        При отсутствии отчества возвращается фамилия и инициал имени.
        """
        name_i = self.first_name[:1].upper() + "."
        if patronymic_i := self.patronymic[:1]:
            patronymic_i = patronymic_i.upper() + "."
        return f"{self.last_name} {name_i} {patronymic_i}"

    def get_full_name(self) -> str:
        """Получает полную строку с ФИО пользователя."""
        return (
            f"{self.last_name[:UserConstans.QUERY_SET_LENGTH]} "
            f"{self.first_name[:UserConstans.QUERY_SET_LENGTH]} "
            f"{self.patronymic[:UserConstans.QUERY_SET_LENGTH]}"
        )

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Отправляет email пользователю с заданным сообщением."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def save(
        self,
        force_insert: bool = False,  # type: ignore[override]
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ) -> None:
        """
        Переопределенный метод модели.

        При любом сохранении устанавливает группу пользователя в зависимости
        от его роли.
        """
        super().save(
            force_insert,
            force_update,
            using,
            update_fields,
        )  # type: ignore
        self.set_group()

    @property
    def is_agent(self):
        """
        Установка атрибута is_agent.

        Представитель команды - имеет возможность редактировать данные детей в
        своей команде. Просматривать некоторые данные по игрокам в других
        командах (ФИО, возраст, спортивный класс, тип заболевания).
        Выгружать формы по своей команде. Загружать сканы справок.
        """
        return self.role == Role.AGENT

    @property
    def is_moderator(self):
        """
        Установка атрибута is_moderator.

        Модератор - имеет возможности вносить данные по определенному ребенку,
        не может добавлять новых пользователей и удалять детей, команды.
        """
        return self.role == Role.MODERATOR

    @property
    def is_admin(self):
        """Администратор - имеет неограниченные права управления на проекте."""
        return self.role == Role.ADMIN or self.is_staff

    def set_group(self):
        """Добавляет пользователя в группу в зависимости от его роли."""
        if not (group_name := GROUPS_BY_ROLE.get(self.role, None)):
            raise ValidationError(
                f"Неизвестная роль пользователя: " f"{self.role}",
            )
        if group := ProxyGroup.get_by_name(group_name):
            self.groups.clear()
            self.groups.add(group)
        else:
            raise Http404(f"Не найдена группа {group_name}")


class ProxyGroup(Group):
    """
    Обычная группа django.

    Класс необходим для регистрации модели в приложении "пользователи".
    """

    class Meta:
        proxy = True
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        """Метод, использующий поле name для строкового представления."""
        return self.name

    @classmethod
    def get_by_name(cls, name: str) -> Group | None:
        """
        Возвращает группу по полю "name".

        Предварительно проверяет наличие таковой группы.
        ВНИМАНИЕ!!! Метод не вызывает исключения при отсутствии в БД искомой
        группы, а вместо исключения возвращает None.
        """
        if (obj := cls.objects.filter(name=name)).exists():
            return obj.first()
        return None

adaptive_hockey_federation/main/controllers/ajax.py
from django.http import JsonResponse

from main.models import DisciplineLevel, DisciplineName


def load_discipline_levels(request):
    """
    Представление для получения списка уровней дисциплин по ID дисциплины.

    Используется в формах создания/редактирования данных игрока.
    """
    discipline_level_id = request.GET.get("discipline_level_id")
    try:
        discipline_statuses = DisciplineLevel.objects.filter(
            discipline_name_id=discipline_level_id,
        ).all()
    except ValueError:
        return JsonResponse([], safe=False)
    else:
        return JsonResponse(
            list(discipline_statuses.values("id", "name")),
            safe=False,
        )


def filter_discipline_search(request):
    """Представления для поиска, получения списка дисциплин."""
    disciplines = DisciplineName.objects.all().values("name")
    return JsonResponse(list(disciplines), safe=False)

adaptive_hockey_federation/main/controllers/main_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector
from django.views.generic.list import ListView
from main.models import Player
from main.schemas.main_schema import get_main_table_data


class MainView(
    LoginRequiredMixin,
    ListView,
):
    """Main_view. Поиск игроков по фамилии/имени."""

    model = Player
    template_name = "main/home/main.html"
    context_object_name = "main"
    fields = [
        "id",
        "surname",
        "name",
        "birthday",
        "gender",
        "number",
        "discipline_name",
        "discipline_level",
        "diagnosis",
    ]

    def get_queryset(self):
        """Получить набор QuerySet."""
        query = self.request.GET.get("search")
        search_vector = SearchVector("surname", "name")
        queryset = None
        if query:
            queryset = Player.objects.annotate(search=search_vector).filter(
                search=query,
            )
            queryset = (
                queryset.select_related("diagnosis")
                .select_related("discipline_name")
                .order_by("surname")
            )

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        """Получить словарь context для шаблона страницы."""
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("search")
        if search:
            table_head = {}
            for field in self.fields:
                if field != "id":
                    table_head[field] = Player._meta.get_field(
                        field,
                    ).verbose_name
            context["table_head"] = table_head
            context["table_data"] = get_main_table_data(context)
        return context

adaptive_hockey_federation/main/controllers/mixins.py
from main.models import Diagnosis


class DiagnosisListMixin:
    """Миксин для использования в видах редактирования и создания команд."""

    @staticmethod
    def get_diagnosis():
        """Возвращает список диагнозов из БД."""
        return Diagnosis.objects.values_list("name", flat=True)

adaptive_hockey_federation/main/controllers/utils.py
from core.constants import FileConstants
from django.urls import reverse
from main.models import Player, Team


def get_player_href(player: Player) -> dict[str, str]:
    """Возвращает словарь с информацией для ссылки на игрока."""
    url = reverse("main:player_id", args=[player.id])
    name = " ".join((player.surname, player.name))
    return {"name": name, "url": url}


def get_team_href(team: Team) -> dict[str, str]:
    """Возвращает словарь с информацией для ссылки на команду."""
    url = reverse("main:teams_id", args=[team.id])
    name = team.name
    return {"name": name, "url": url}


def errormessage() -> str:
    return (
        "Максимальный размер файла "
        + FileConstants.MAX_UPLOAD_SIZE_MB
        + ", допустимые разрешения "
        + ", ".join(FileConstants.FILE_RESOLUTION)
    )

adaptive_hockey_federation/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def main(request):
    return render(request, "main/home/main.html")

adaptive_hockey_federation/templates/main/teams_id/button_create_team_member.html
<div class="dropdown">
    <button class="border border-2 border-white p-2 px-4 drawler_menu dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        + Добавить
    </button>
    <ul class="dropdown-menu" style="background-color: #64C2D1" aria-labelledby="dropdownMenuButton1">
      <li><a class="dropdown-item drawler_menu" style="color: #fff" href="{% url 'main:player_create' %}?team={{ team.id }}">Игрок</a></li>
      <li><a class="dropdown-item drawler_menu" style="color: #fff" href="{% url 'main:staff_create' %}?team={{ team.id }}">Сотрудник</a></li>
    </ul>
</div>

adaptive_hockey_federation/templates/main/teams_id/cell_button.html
<a href="{{ url }}" class="btn btn-secondary text-white"
    style="background-color: #64C2D1; border: 1px solid #fff;"
    role="button">{{ name }}
</a>

adaptive_hockey_federation/templates/main/teams_id/create_delete_buttons.html
{% load static %}
{%if user.is_staff %}
<td class="border rounded-md">
  <div class="items__group">
    <form action="{% url 'users:user_update' table_string.id %}" method="post">
      {% csrf_token %}
      <button class="btns-edit-del" type="submit" {% if perms.users.change_user %} activate {% else %} disabled {% endif %}>
        {% include 'base/edit_icon.html' %}
      </button>
    </form>
    <form action="{% url 'users:user_delete' table_string.id %}" method="post" >
      {% csrf_token %}
      <button class="btns-edit-del" type="submit" {% if perms.users.delete_user %} activate {% else %} disabled {% endif %} onclick="return confirm('Вы точно хотите удалить пользователя {{ table_string.name }}?');"></a>
        {% include 'base/delete_icon.html' %}
      </button>
    </form>
  </div>
</td>
{% endif %}

adaptive_hockey_federation/templates/main/teams_id/edit_delete_button_players.html
{% load static %}
<td class="border rounded-md">
  <div class="items__group">
    <a href="{% url 'main:player_id_edit' pk=table_string.id %}">
      <button class="btns-edit-del" type="submit" {% if 'main.change_player' in perms %} activate {% else %} disabled {% endif %}>
        {% include 'base/edit_icon.html' %}
      </button>
    </a>
    {% if user.is_staff %}
      <form action="{% url 'main:player_id_delete' pk=table_string.id %}" method="post" >
        {% csrf_token %}
          <button class="btns-edit-del" type="submit" {% if 'main.delete_player' in perms %} activate {% else %} disabled {% endif %} onclick="return confirm('Вы точно хотите удалить пользователя {{ table_string.name }}?');"></a>
            {% include 'base/delete_icon.html' %}
          </button>
      </form>
    {% endif %}
  </div>
</td>

adaptive_hockey_federation/templates/main/teams_id/edit_delete_button_staffs.html
{% load static %}
{% if user.is_staff %}
  <td class="border rounded-md">
    <div class="items__group">
      <a href="{% url 'main:staff_id_team_edit' pk=table_string.id position=table_string.staff_position_slug %}">
        <button class="btns-edit-del" type="submit"
            {% if 'main.change_staff' in perms %} activate {% else %}
                disabled {% endif %}>
          {% include 'base/edit_icon.html' %}
        </button>
      </a>
      <form action="{% url 'main:fire_staff_from_team' team_id=team.id staff_team_member_id=table_string.id %}"
            method="post">
        {% csrf_token %}
        <button class="btns-edit-del" type="submit"
            {% if 'main.delete_staff' in perms %} activate {% else %}
                disabled {% endif %}
                onclick="return confirm('Вы точно хотите отстранить сотрудника {{ table_string.name }}?');"></a>
          {% include 'base/delete_icon.html' %}
        </button>
      </form>
    </div>
  </td>
{% endif %}

adaptive_hockey_federation/templates/main/teams_id/table.html
{% load static %}
<div class="table-responsive scroll-class">
  <table class="table-table">
    <thead>
      <tr>
        {% for head_item in table_head.values %}
        <th class="col">{{ head_item }}</th>
        {% endfor %}
        {% if table_name == "players" and request.user == team.curator or request.user.is_admin %}
          <th>
            <div class="cell__buttons">
              {% include 'base/active_edit_icon.html' %}
              {% include 'base/active_delete_icon.html' %}
            </div>
          </th>
        {% endif %}
      </tr>
    </thead>
    <tbody>
      {% for table_string in table_data %}
      <tr>
        {% for cell_name, cell_value in table_string.items %}
          {% if forloop.counter0 == 0 and 'url' in table_string %}
            <td class="rounded-md">
              <a href="{{ table_string.url }}">{{ cell_value }} </a>
            </td>
          {% elif cell_name == '_ref_' %}
            {% if cell_value.type == 'button' %}
              <td class="rounded-md">
                {% include 'teams_id/cell_button.html' with url=cell_value.url name=cell_value.name %}
              </td>
            {% else %}
              <td class="rounded-md">
                <a href="{{ cell_value.url }}">{{ cell_value.name }} </a>
              </td>
            {% endif %}
          {% elif cell_name == 'full_name_link' %}
            <td class="rounded-md">
              {% if request.user.is_admin or request.user == team.curator %}
                <a href="{{ cell_value.url }}">{{ cell_value.name }}</a>
              {% else %}
                {{ cell_value.name }}
              {% endif %}
            </td>
          {% elif cell_name != 'url' and cell_name != 'id' and cell_name != 'pk' and cell_name != 'staff_position_slug'%}
            <td class="rounded-md">{{ cell_value }}</td>
          {% endif %}
        {% endfor %}
        {% if table_name == 'players' %}
          {% if request.user.is_admin or request.user == team.curator %}
            {% include "main/teams_id/edit_delete_button_players.html" %}
          {% endif %}
        {% elif table_name == 'staff' %}
          {% include "main/teams_id/edit_delete_button_staffs.html" %}
        {% else %}
          <td>
            <div class="cell__buttons">
              {% include 'base/active_edit_icon.html' %}
              {% include 'base/active_delete_icon.html' %}
            </div>
          </td>
        {% endif %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

adaptive_hockey_federation/templates/main/teams_id/teams_id.html
{% extends 'base/base.html' %}
{% load user_filters %}
{% block title %}
  Профиль команды: {{ team }}
{% endblock %}
{% block content %}
  <h2 class="text-center mb-4">Команда: {{ team }}</h2>
  {% for staff in staff_table %}
    <div class="container">
      <h3 class="text-start mb-4">{{ staff.position }}</h3>
      {% include 'main/teams_id/table.html' with table_head=staff.head table_data=staff.data table_name='staff' %}

      <form
        method="post"
        {% if action_url %}
        action="{% url action_url %}"
{#          enctype="multipart/form-data"#}
        {% endif %}
      >
        {% csrf_token %}
        {% if request.user == team.curator or user.is_staff %}
          {% for field in staff.add_staff_form %}
            <div class="tw-w-full tw-flex tw-justify-center">
              <div class="row my-1 tw-min-w-[70%] tw-max-w-[80%]">
                <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                {% include 'main/teams_id/components/staff_search_field.html' %}
                {% if field.errors %}
                  <small style="color: red" class="error">{{ field.errors|striptags  }}</small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
        {% endif %}
          {% if request.user == team.curator or user.is_staff %}
            <button type="submit" class="update_btn tw-rounded-lg"
                    name="btn_add_staff"
                    value="{{ forloop.counter0 }}">
              Добавить
            </button>
          {% endif %}
      </form>
    </div>
  {% endfor %}
  <div class="container">
    <h3 class="text-start mb-4">{{ players_table.name }}</h3>
    {% include 'main/teams_id/table.html' with table_head=players_table.head table_data=players_table.data table_name='players' %}
  </div>
{% endblock content %}