adaptive_hockey_federation/adaptive_hockey_federation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

adaptive_hockey_federation/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("users.urls", namespace="users")),
    path("", include("competitions.urls", namespace="competitions")),
    path("", include("analytics.urls", namespace="analytics")),
    path("", include("unloads.urls", namespace="unloads")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.not_found"
handler403 = "core.views.forbidden"
handler500 = "core.views.internal_server_error"

adaptive_hockey_federation/main/urls.py
from django.urls import include, path
from main.controllers import (
    ajax,
    main_views,
    player_views,
    staff_views,
    team_views,
)

app_name = "main"

main_urlpatterns = [
    path("", main_views.MainView.as_view(), name="main"),
]

players_urlpatterns = [
    path("", player_views.PlayersListView.as_view(), name="players"),
    path(
        "create/",
        player_views.PlayerIDCreateView.as_view(),
        name="player_create",
    ),
    path(
        "<int:pk>/",
        player_views.PlayerIdView.as_view(),
        name="player_id",
    ),
    path(
        "<int:pk>/edit/",
        player_views.PlayerIDEditView.as_view(),
        name="player_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        player_views.PlayerIDDeleteView.as_view(),
        name="player_id_delete",
    ),
    path(
        "deleted/",
        player_views.player_id_deleted,
        name="player_id_deleted",
    ),
]

teams_urlpatterns = [
    path("", team_views.TeamListView.as_view(), name="teams"),
    path(
        "create/",
        team_views.CreateTeamView.as_view(),
        name="team_create",
    ),
    path(
        "<int:team_id>/",
        team_views.TeamIdView.as_view(),
        name="teams_id",
    ),
    path(
        "<int:team_id>/edit/",
        team_views.UpdateTeamView.as_view(),
        name="team_update",
    ),
    path(
        "<int:team_id>/delete/",
        team_views.DeleteTeamView.as_view(),
        name="team_delete",
    ),
    path(
        "<int:team_id>/fire_staff/<int:staff_team_member_id>/",
        team_views.FireStaffFromTeam.as_view(),
        name="fire_staff_from_team",
    ),
]

staffs_urlpatterns = [
    path(
        "",
        staff_views.StaffMemberListView.as_view(),
        name="staffs",
    ),
    path(
        "create/",
        staff_views.StaffMemberIdCreateView.as_view(),
        name="staff_create",
    ),
    path(
        "<int:pk>/",
        staff_views.StaffMemberIdView.as_view(),
        name="staff_id",
    ),
    path(
        "<int:pk>/edit/",
        staff_views.StaffMemberIdEditView.as_view(),
        name="staff_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        staff_views.StaffMemberIdDeleteView.as_view(),
        name="staff_id_delete",
    ),
    path(
        "<int:pk>/<slug:position>/team/create/",
        staff_views.StaffMemberIdTeamCreateView.as_view(),
        name="staff_id_team_create",
    ),
    path(
        "<int:pk>/<slug:position>/team/edit/",
        staff_views.StaffMemberIDTeamEditView.as_view(),
        name="staff_id_team_edit",
    ),
    path(
        "<int:pk>/<slug:position>/team/delete/",
        staff_views.StaffMemberIdTeamDeleteView.as_view(),
        name="staff_id_team_delete",
    ),
]

ajax_urlpatterns = [
    path(
        "load-discipline-levels/",
        ajax.load_discipline_levels,
        name="ajax_load_discipline_levels",
    ),
    path(
        "filter-discipline-search/",
        ajax.filter_discipline_search,
        name="ajax_filter_discipline_search",
    ),
]

urlpatterns = [
    path("", include(main_urlpatterns)),
    path("players/", include(players_urlpatterns)),
    path("teams/", include(teams_urlpatterns)),
    path("staffs/", include(staffs_urlpatterns)),
    path("ajax/", include(ajax_urlpatterns)),
]

adaptive_hockey_federation/users/urls.py
from django.urls import include, path
from users.views import (
    CreateUserView,
    DeleteUserView,
    PasswordSetView,
    UpdateUserView,
    UsersListView,
)

app_name = "users"

users_urlpatterns = [
    path(
        "",
        UsersListView.as_view(),
        name="users",
    ),
    path(
        "create/",
        CreateUserView.as_view(),
        name="user_create",
    ),
    path(
        "<int:pk>/edit/",
        UpdateUserView.as_view(),
        name="user_update",
    ),
    path(
        "<int:pk>/delete/",
        DeleteUserView.as_view(),
        name="user_delete",
    ),
    path(
        "set_password/<uidb64>/<token>/",
        PasswordSetView.as_view(),
        name="password_set",
    ),
]

urlpatterns = [
    path("users/", include(users_urlpatterns)),
]

adaptive_hockey_federation/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    PermissionRequiredMixin,
)
from django.contrib.auth.views import PasswordResetConfirmView
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from main.models import Team
from users.forms import CustomUserCreateForm, CustomUserUpdateForm
from users.utilits.send_mails import send_password_reset_email

User = get_user_model()


class UsersListView(
    LoginRequiredMixin,
    PermissionRequiredMixin,
    ListView,
):
    """Представление для получения списка пользователей."""

    model = User
    template_name = "main/users/list.html"
    permission_required = "users.list_view_user"
    permission_denied_message = (
        "Отсутствует разрешение на просмотр списка пользователей."
    )
    context_object_name = "users"
    paginate_by = 10

    def get_queryset(self):
        """Получить набор QuerySet."""
        queryset = super().get_queryset().order_by("last_name")
        search_params = self.request.GET.dict()
        search_column = search_params.get("search_column")
        search = search_params.get("search")
        if search_column:
            if search_column and search_column.lower() in ["все", "all"]:
                or_lookup = (
                    Q(first_name__icontains=search)
                    | Q(last_name__icontains=search)
                    | Q(patronymic__icontains=search)
                    | Q(role__icontains=search)
                    | Q(email__icontains=search)
                    | Q(phone__icontains=search)
                    | Q(date_joined__icontains=search)
                )
                queryset = queryset.filter(or_lookup)
            elif search_column == "name":
                queryset = queryset.filter(
                    Q(first_name__icontains=search)
                    | Q(last_name__icontains=search)
                    | Q(patronymic__icontains=search),
                )
            elif search_column == "date":
                queryset = queryset.filter(
                    Q(date_joined__year__icontains=search_params["year"])
                    & Q(
                        date_joined__month__icontains=search_params[
                            "month"
                        ].lstrip("0"),
                    )
                    & Q(
                        date_joined__day__icontains=search_params[
                            "day"
                        ].lstrip("0"),
                    ),
                )
            else:
                search_fields = {
                    "role": "role",
                    "email": "email",
                    "phone": "phone",
                }
                queryset = queryset.filter(
                    **{f"{search_fields[search_column]}__icontains": search},
                )
        return queryset.order_by("last_name")

    def get_context_data(self, **kwargs):
        """Получить словарь context для шаблона страницы."""
        context = super().get_context_data(**kwargs)
        users = context["users"]
        table_data = []
        for user in users:
            table_data.append(
                {
                    "name": user.get_full_name(),
                    "date": user.date_joined,
                    "role": user.get_role_display(),
                    "email": user.email,
                    "phone": user.phone,
                    "id": user.pk,
                },
            )
        context["table_head"] = {
            "name": "Имя",
            "date": "Дата регистрации",
            "role": "Роль",
            "email": "Email",
            "phone": "Телефон",
        }
        context["table_data"] = table_data
        return context


class UpdateUserView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    """Представление для обновления пользователя."""

    model = User
    form_class = CustomUserUpdateForm
    template_name = "main/users/user_create_edit.html"
    permission_required = "users.change_user"
    permission_denied_message = (
        "Отсутствует разрешение на изменение пользователя."
    )

    def get_success_url(self):
        """Перенаправить на указанный адрес при успешном обновлении."""
        return reverse("users:users")

    def get_object(self, queryset=None):
        """Получить объект по id или выбросить ошибку 404."""
        return get_object_or_404(User, id=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        """Получить словарь context для шаблона страницы."""
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Редактирование профиля пользователя"
        return context

    def form_valid(self, form):
        """Запустить валидацию формы."""
        if form.is_valid():
            user = form.save()
            Team.objects.filter(curator=user).update(curator=None)
            choice_teams = form.cleaned_data["team"]
            if choice_teams is not None:
                for team in choice_teams:
                    team.curator = user
                    team.save()
        return super().form_valid(form)


class DeleteUserView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    """Представление для удаления пользователя."""

    object = User
    model = User
    success_url = "/users"
    permission_required = "users.delete_user"
    permission_denied_message = (
        "Отсутствует разрешение на удаление пользователей."
    )


class CreateUserView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    """Представление для создания пользователя."""

    model = User
    form_class = CustomUserCreateForm
    template_name = "main/users/user_create_edit.html"
    success_url = "/users"
    permission_required = "users.add_user"
    permission_denied_message = (
        "Отсутствует разрешение на создание пользователей."
    )

    def get_context_data(self, **kwargs):
        """Получить словарь context для шаблона страницы."""
        context = super().get_context_data(**kwargs)
        context["page_title"] = "Создание пользователя"
        return context

    def form_valid(self, form):
        """Запустить валидацию формы."""
        if form.is_valid():
            user = form.save()
            choice_teams = form.cleaned_data["team"]
            if choice_teams is not None:
                for team in choice_teams:
                    team.curator = user
                    team.save()
            send_password_reset_email(user)
        return super().form_valid(form)


class PasswordSetView(PasswordResetConfirmView):
    """Представление для изменения пароля пользователя."""

    success_url = reverse_lazy("users:users")

    def form_valid(self, form):
        """Запустить валидацию формы."""
        response = super().form_valid(form)
        self.user.save()
        return response

adaptive_hockey_federation/templates/users/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% load static %}
  {% include 'users/includes/head.html' %}
  <title>
    {% block title %} {% endblock %}
  </title>
</head>
<body>
  <header>
    {% include 'users/includes/header.html'%}
  </header>
  {% block content %}
      Контент не подвезли
  {% endblock %}
  {% with request.resolver_match.view_name as view_name %}
    {% if view_name == 'users:login'%}
      {% include 'users/includes/footer.html'%}
    {% endif %}
  {% endwith %}
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

adaptive_hockey_federation/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %} Вы вышли из системы {% endblock %}
{% block content %}
  <div class="card-body">
    <p>
      Вы вышли из своей учётной записи. Ждём вас снова!
    </p>
  </div>
  <div class="card-footer">
    <div class="border border-white rounded px-2">
      <a href="{% url 'main:main' %}">
        <b class="text-xl" style="color: #340061;">На главную</b>
      </a>
    </div>
  </div>
{% endblock %}

adaptive_hockey_federation/templates/users/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
  {% load static %}
  {% load user_filters %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel ="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <script src="{% static 'js/windows.js' %}"></script>
  <title> Логин</title>
</head>
<body>
  <div class='header'>
    <div class='container'>
      <div class='header-line'>
        <div class='header-logo'>
          <img src={% static "img/logo.png" %} width="250px" height="250px">
        </div>
        <div class='header-ellipse'>
          <img src={% static "img/ellipse.png" %} width="520px" height="500px">
        </div>
        <div class='header-rect'>
          <img src={% static "img/rect.png" %} width="990px" height="345px">
        </div>
        <div>
          <p class='header-text'>Мир хоккея для особенных детей</p>
        </div>
      </div>
      </div>
      <div class='registration-form'>
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-md-3 p-5">
              {% include 'includes/forms_errors.html' %}
              <div class="form-popup" id="myForm">
                <div class="form-container_reset">
                    <h1>Забыли пароль</h1>
                    <form action="*" method="post">
                      {% csrf_token %}
                      <div class='reset_form_input'>
                        <input type="text" placeholder="Е-майл/Телефон" name="name" class="text_inbox"></div>
                      <div class='submit_button_email'>
                        <button type="button" class="btn cancel"  name="email_input">Подтвердить</button></div>
                    </form>
                    <form action="*" method="post">
                      {% csrf_token %}
                      <div class='reset_form_input'>
                        <input type="text" placeholder="Код" name="name" class="text_inbox"></div>
                      <div class='submit_button_email'>
                        <button type="button" class="btn cancel"  name="code_input" onclick="openRestoreForm()">Войти</button></div>
                    </form>
                </div>
              </div>
              <div class="form-popup" id="RestoreForm">
                <div class="form-container_reset">
                  <form action="*" method="post">
                    {% csrf_token %}
                    <h1>Обновить пароль</h1>
                    <div class='reset_form_input'>
                      <input type="text" placeholder="Е-майл/Телефон" name="name" class="text_inbox">
                    </div>
                    <div class='reset_form_input'>
                      <input type="text" placeholder="Новый пароль" name="name"class="text_inbox">
                    </div>
                    <div class='reset_form_input'>
                      <input type="text" placeholder="Повторить пароль" name="name"class="text_inbox">
                    </div>
                    <div class='submit_button_password'>
                      <button type="button" class="btn cancel"  name="enter_site" onclick="closeRestoreForm()">Войти</button>
                    </div>
                  </form>
                </div>
              </div>
              <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row my-3"
                  {% if field.field.required %}
                  aria-required="true"
                  {% else %}
                  aria-required="false"
                  {% endif %}
                  >
                  {{ field|addclass:'form-control' }}
                </div>
                {% endfor %}
                <div class="btns">
                  <button class="button_on" type="submit">
                    Войти
                  </button>
                  <button class="open-button" type="button" onclick="openForm()">Забыли пароль</button>
                </div>
              </form>
            </div>
            <div class='btn_back'>
              <button class="button_out" type="button">
                <a class='text' href="https://paraicehockey.ru/">На сайт</a>
              </button>
            </dev>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

adaptive_hockey_federation/templates/users/table.html
{% load static %}
<div class="table-responsive">
  <table class="table table-bordered">
    <thead>
      <tr>
        {% for head_item in table_head.values %}
        <th class="col">{{ head_item }}</th>
        {% endfor %}
        <th class="col">
          <div class="row">
            <div class="col text-right">
              <img src="{% static 'img/edit.png' %}" class="float-end">
            </div>
            <div class="col text-left">
              <img src="{% static 'img/delete.png' %}" class="float-start">
            </div>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for table_string in table_data %}
      <tr>
        {% for cell_name, cell_value in table_string.items %}
          {% if forloop.counter0 == 0 and 'url' in table_string %}
            <td class="border rounded-md table-light">
              <a href="{{ table_string.url }}">{{ cell_value }} </a>
            </td>
          {% elif cell_name == '_ref_' %}
            {% if cell_value.type == 'button' %}
              <td class="border rounded-md table-light">
                {% include 'users/cell_button.html' with url=cell_value.url name=cell_value.name %}
              </td>
            {% else %}
              <td class="border rounded-md table-light">
                <a href="{{ cell_value.url }}">{{ cell_value.name }} </a>
              </td>
            {% endif %}
          {% elif cell_name != 'url' and cell_name != 'id'%}
            <td class="border rounded-md table-light">{{ cell_value }}</td>
          {% endif %}
        {% endfor %}
        {% with request.resolver_match.view_name as view_name %}
        {% if view_name == 'users:users' %}
        {% include "users/create_delete_buttons.html" %}
        {% else %}
        <td>
          <button type="button"><img src="{% static 'img/edit.png' %}"></button>
          <button type="button"><img src="{% static 'img/delete.png' %}"></button>
        </td>
        {% endif %}
        {% endwith %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>