adaptive_hockey_federation/adaptive_hockey_federation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

adaptive_hockey_federation/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("users.urls", namespace="users")),
    path("", include("competitions.urls", namespace="competitions")),
    path("", include("analytics.urls", namespace="analytics")),
    path("", include("unloads.urls", namespace="unloads")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.not_found"
handler403 = "core.views.forbidden"
handler500 = "core.views.internal_server_error"

adaptive_hockey_federation/main/urls.py
from django.urls import include, path
from main.controllers import (
    ajax,
    main_views,
    player_views,
    staff_views,
    team_views,
)

app_name = "main"

main_urlpatterns = [
    path("", main_views.MainView.as_view(), name="main"),
]

players_urlpatterns = [
    path("", player_views.PlayersListView.as_view(), name="players"),
    path(
        "create/",
        player_views.PlayerIDCreateView.as_view(),
        name="player_create",
    ),
    path(
        "<int:pk>/",
        player_views.PlayerIdView.as_view(),
        name="player_id",
    ),
    path(
        "<int:pk>/edit/",
        player_views.PlayerIDEditView.as_view(),
        name="player_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        player_views.PlayerIDDeleteView.as_view(),
        name="player_id_delete",
    ),
    path(
        "deleted/",
        player_views.player_id_deleted,
        name="player_id_deleted",
    ),
]

teams_urlpatterns = [
    path("", team_views.TeamListView.as_view(), name="teams"),
    path(
        "create/",
        team_views.CreateTeamView.as_view(),
        name="team_create",
    ),
    path(
        "<int:team_id>/",
        team_views.TeamIdView.as_view(),
        name="teams_id",
    ),
    path(
        "<int:team_id>/edit/",
        team_views.UpdateTeamView.as_view(),
        name="team_update",
    ),
    path(
        "<int:team_id>/delete/",
        team_views.DeleteTeamView.as_view(),
        name="team_delete",
    ),
    path(
        "<int:team_id>/fire_staff/<int:staff_team_member_id>/",
        team_views.FireStaffFromTeam.as_view(),
        name="fire_staff_from_team",
    ),
]

staffs_urlpatterns = [
    path(
        "",
        staff_views.StaffMemberListView.as_view(),
        name="staffs",
    ),
    path(
        "create/",
        staff_views.StaffMemberIdCreateView.as_view(),
        name="staff_create",
    ),
    path(
        "<int:pk>/",
        staff_views.StaffMemberIdView.as_view(),
        name="staff_id",
    ),
    path(
        "<int:pk>/edit/",
        staff_views.StaffMemberIdEditView.as_view(),
        name="staff_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        staff_views.StaffMemberIdDeleteView.as_view(),
        name="staff_id_delete",
    ),
    path(
        "<int:pk>/<slug:position>/team/create/",
        staff_views.StaffMemberIdTeamCreateView.as_view(),
        name="staff_id_team_create",
    ),
    path(
        "<int:pk>/<slug:position>/team/edit/",
        staff_views.StaffMemberIDTeamEditView.as_view(),
        name="staff_id_team_edit",
    ),
    path(
        "<int:pk>/<slug:position>/team/delete/",
        staff_views.StaffMemberIdTeamDeleteView.as_view(),
        name="staff_id_team_delete",
    ),
]

ajax_urlpatterns = [
    path(
        "load-discipline-levels/",
        ajax.load_discipline_levels,
        name="ajax_load_discipline_levels",
    ),
    path(
        "filter-discipline-search/",
        ajax.filter_discipline_search,
        name="ajax_filter_discipline_search",
    ),
]

urlpatterns = [
    path("", include(main_urlpatterns)),
    path("players/", include(players_urlpatterns)),
    path("teams/", include(teams_urlpatterns)),
    path("staffs/", include(staffs_urlpatterns)),
    path("ajax/", include(ajax_urlpatterns)),
]

adaptive_hockey_federation/users/models.py
from typing import Iterable

from core.constants import GROUPS_BY_ROLE, ROLES_CHOICES, Role, UserConstans
from core.validators import fio_validator
from django.contrib.auth.models import (
    AbstractBaseUser,
    Group,
    PermissionsMixin,
)
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.core.validators import EmailValidator
from django.db import models
from django.http import Http404
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.validators import validate_international_phonenumber
from users.managers import CustomUserManager
from users.validators import zone_code_without_seven_hundred


class User(AbstractBaseUser, PermissionsMixin):
    """
    Кастомная модель пользователя.

    1. Поле 'username' исключено
    2. Идентификатором является поле с адресом электронной почты.
    """

    first_name = models.CharField(
        max_length=UserConstans.NAME_MAX_LENGTH,
        verbose_name=_("Имя"),
        help_text=_("Имя"),
        validators=[fio_validator()],
    )
    last_name = models.CharField(
        max_length=UserConstans.NAME_MAX_LENGTH,
        verbose_name=_("Фамилия"),
        help_text=_("Фамилия"),
        validators=[fio_validator()],
    )
    patronymic = models.CharField(
        blank=True,
        max_length=UserConstans.NAME_MAX_LENGTH,
        verbose_name=_("Отчество"),
        help_text=_("Отчество"),
        validators=[fio_validator()],
    )
    role = models.CharField(
        choices=ROLES_CHOICES,
        default=Role.AGENT,
        max_length=max(len(role) for role, _ in ROLES_CHOICES),
        verbose_name=_("Роль"),
        help_text=_("Уровень прав доступа"),
    )
    email = models.EmailField(
        max_length=UserConstans.EMAIL_MAX_LENGTH,
        unique=True,
        validators=(
            EmailValidator(
                message="Используйте корректный адрес электронной почты. "
                "Адрес должен быть не длиннее 150 символов. "
                "Допускается использование латинских букв, "
                "цифр и символов @/./+/-/_",
            ),
        ),
        verbose_name=_("Электронная почта"),
        help_text=_("Электронная почта"),
    )
    phone = PhoneNumberField(
        blank=True,
        validators=[
            validate_international_phonenumber,
            zone_code_without_seven_hundred,
        ],
        verbose_name=_("Актуальный номер телефона"),
        help_text=_("Номер телефона, допустимый формат - +7 ХХХ ХХХ ХХ ХХ"),
    )
    date_joined = models.DateTimeField(
        default=timezone.now,
        verbose_name=_("Дата регистрации"),
    )
    is_staff = models.BooleanField(
        default=False,
        verbose_name=_("Статус администратора."),
    )
    is_active = models.BooleanField(
        default=True,
        verbose_name=_("Показывает статус он-лайн."),
    )

    objects = CustomUserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "role"]

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")
        ordering = ("last_name",)
        permissions = [
            ("list_view_user", "Can view list of Пользователь"),
        ]

    def clean(self):
        """Метод валидации модели."""
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def __str__(self):
        """Использует метод get_initials() для строкового представления."""
        return self.get_initials()

    def get_initials(self) -> str:
        """
        Возвращает фамилию и инициалы пользователя.

        При отсутствии отчества возвращается фамилия и инициал имени.
        """
        name_i = self.first_name[:1].upper() + "."
        if patronymic_i := self.patronymic[:1]:
            patronymic_i = patronymic_i.upper() + "."
        return f"{self.last_name} {name_i} {patronymic_i}"

    def get_full_name(self) -> str:
        """Получает полную строку с ФИО пользователя."""
        return (
            f"{self.last_name[:UserConstans.QUERY_SET_LENGTH]} "
            f"{self.first_name[:UserConstans.QUERY_SET_LENGTH]} "
            f"{self.patronymic[:UserConstans.QUERY_SET_LENGTH]}"
        )

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Отправляет email пользователю с заданным сообщением."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def save(
        self,
        force_insert: bool = False,  # type: ignore[override]
        force_update: bool = False,
        using: str | None = None,
        update_fields: Iterable[str] | None = None,
    ) -> None:
        """
        Переопределенный метод модели.

        При любом сохранении устанавливает группу пользователя в зависимости
        от его роли.
        """
        super().save(
            force_insert,
            force_update,
            using,
            update_fields,
        )  # type: ignore
        self.set_group()

    @property
    def is_agent(self):
        """
        Установка атрибута is_agent.

        Представитель команды - имеет возможность редактировать данные детей в
        своей команде. Просматривать некоторые данные по игрокам в других
        командах (ФИО, возраст, спортивный класс, тип заболевания).
        Выгружать формы по своей команде. Загружать сканы справок.
        """
        return self.role == Role.AGENT

    @property
    def is_moderator(self):
        """
        Установка атрибута is_moderator.

        Модератор - имеет возможности вносить данные по определенному ребенку,
        не может добавлять новых пользователей и удалять детей, команды.
        """
        return self.role == Role.MODERATOR

    @property
    def is_admin(self):
        """Администратор - имеет неограниченные права управления на проекте."""
        return self.role == Role.ADMIN or self.is_staff

    def set_group(self):
        """Добавляет пользователя в группу в зависимости от его роли."""
        if not (group_name := GROUPS_BY_ROLE.get(self.role, None)):
            raise ValidationError(
                f"Неизвестная роль пользователя: " f"{self.role}",
            )
        if group := ProxyGroup.get_by_name(group_name):
            self.groups.clear()
            self.groups.add(group)
        else:
            raise Http404(f"Не найдена группа {group_name}")


class ProxyGroup(Group):
    """
    Обычная группа django.

    Класс необходим для регистрации модели в приложении "пользователи".
    """

    class Meta:
        proxy = True
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        """Метод, использующий поле name для строкового представления."""
        return self.name

    @classmethod
    def get_by_name(cls, name: str) -> Group | None:
        """
        Возвращает группу по полю "name".

        Предварительно проверяет наличие таковой группы.
        ВНИМАНИЕ!!! Метод не вызывает исключения при отсутствии в БД искомой
        группы, а вместо исключения возвращает None.
        """
        if (obj := cls.objects.filter(name=name)).exists():
            return obj.first()
        return None

adaptive_hockey_federation/main/controllers/ajax.py
from django.http import JsonResponse

from main.models import DisciplineLevel, DisciplineName


def load_discipline_levels(request):
    """
    Представление для получения списка уровней дисциплин по ID дисциплины.

    Используется в формах создания/редактирования данных игрока.
    """
    discipline_level_id = request.GET.get("discipline_level_id")
    try:
        discipline_statuses = DisciplineLevel.objects.filter(
            discipline_name_id=discipline_level_id,
        ).all()
    except ValueError:
        return JsonResponse([], safe=False)
    else:
        return JsonResponse(
            list(discipline_statuses.values("id", "name")),
            safe=False,
        )


def filter_discipline_search(request):
    """Представления для поиска, получения списка дисциплин."""
    disciplines = DisciplineName.objects.all().values("name")
    return JsonResponse(list(disciplines), safe=False)

adaptive_hockey_federation/main/controllers/main_views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.postgres.search import SearchVector
from django.views.generic.list import ListView
from main.models import Player
from main.schemas.main_schema import get_main_table_data


class MainView(
    LoginRequiredMixin,
    ListView,
):
    """Main_view. Поиск игроков по фамилии/имени."""

    model = Player
    template_name = "main/home/main.html"
    context_object_name = "main"
    fields = [
        "id",
        "surname",
        "name",
        "birthday",
        "gender",
        "number",
        "discipline_name",
        "discipline_level",
        "diagnosis",
    ]

    def get_queryset(self):
        """Получить набор QuerySet."""
        query = self.request.GET.get("search")
        search_vector = SearchVector("surname", "name")
        queryset = None
        if query:
            queryset = Player.objects.annotate(search=search_vector).filter(
                search=query,
            )
            queryset = (
                queryset.select_related("diagnosis")
                .select_related("discipline_name")
                .order_by("surname")
            )

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        """Получить словарь context для шаблона страницы."""
        context = super().get_context_data(**kwargs)
        search = self.request.GET.get("search")
        if search:
            table_head = {}
            for field in self.fields:
                if field != "id":
                    table_head[field] = Player._meta.get_field(
                        field,
                    ).verbose_name
            context["table_head"] = table_head
            context["table_data"] = get_main_table_data(context)
        return context

adaptive_hockey_federation/main/controllers/mixins.py
from main.models import Diagnosis


class DiagnosisListMixin:
    """Миксин для использования в видах редактирования и создания команд."""

    @staticmethod
    def get_diagnosis():
        """Возвращает список диагнозов из БД."""
        return Diagnosis.objects.values_list("name", flat=True)

adaptive_hockey_federation/main/controllers/utils.py
from core.constants import FileConstants
from django.urls import reverse
from main.models import Player, Team


def get_player_href(player: Player) -> dict[str, str]:
    """Возвращает словарь с информацией для ссылки на игрока."""
    url = reverse("main:player_id", args=[player.id])
    name = " ".join((player.surname, player.name))
    return {"name": name, "url": url}


def get_team_href(team: Team) -> dict[str, str]:
    """Возвращает словарь с информацией для ссылки на команду."""
    url = reverse("main:teams_id", args=[team.id])
    name = team.name
    return {"name": name, "url": url}


def errormessage() -> str:
    return (
        "Максимальный размер файла "
        + FileConstants.MAX_UPLOAD_SIZE_MB
        + ", допустимые разрешения "
        + ", ".join(FileConstants.FILE_RESOLUTION)
    )

adaptive_hockey_federation/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def main(request):
    return render(request, "main/home/main.html")

adaptive_hockey_federation/templates/main/player_id/MOCK_player_id_video_response.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
  Запрос видео
{% endblock %}

{% block content %}
  <h2 class="text-center mb-4">Видео в обработке</h2>
{% endblock %}

adaptive_hockey_federation/templates/main/player_id/edit_delete_buttons.html
<div class="text-center">
    <div style="display: flex; justify-content: center;">
        <a href="{% url 'main:player_id_edit' pk=player.pk %}" class="btn btn-secondary text-white" style="background-color: #64C2D1; border: 1px solid #fff; margin-right: 10px;">Редактировать</a>
        {% if not user.is_moderator %}
            <form action="{% url 'main:player_id_delete' pk=player.pk %}" method="post" id="deleteForm">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" {% if not perms.users.delete_user %} disabled {% endif %} onclick="return confirm('Вы точно хотите удалить пользователя {{ player.id }}?');">Удалить</button>
            </form>
        {% endif %}
    </div>
</div>

adaptive_hockey_federation/templates/main/player_id/player_id.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
  Профиль игрока
{% endblock %}
{% block content %}
  <h2 class="text-center mb-4">Профиль игрока</h2>
  <div class="container text-start">
    <div class="row">
      <div class="col-md-6">
        <h4 class="text-center mb-4">Личная информация</h4>
        <table class="table-table">
          <tbody>
            {% for field_name, field_value in player_fields_personal %}
              <tr>
                <th scope="row">{{ field_name }}:</th>
                <td>
                  {{ field_value }}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="col-md-6">
        <h4 class="text-center mb-4">Игровая информация</h4>
        <table class="table-table">
          <tbody>
            {% for field_name, field_value in player_fields %}
              <tr>
                <th scope="row">{{ field_name }}:</th>
                <td>
                  {% if field_name == 'Капитан' or field_name == 'Ассистент' %}
                    {% if field_value %}
                      Да
                    {% endif %}
                  {% elif field_name == 'Команда' %}
                    {% for team in field_value %}
                      <a href="{{ team.url }}">{{ team.name }}</a>
                      {% if not forloop.last %}<br>{% endif %}
                    {% endfor %}
                  {% else %}
                    {{ field_value }}
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <div class="container">
          {% include 'main/player_id/video_games_button.html' with player=player %}
        </div>
      </div>

      <div class="col-md-6">
        <h4 class="text-center mb-4">Документы</h4>
        <table class="table-table">
          <tbody>
            {% for doc in player_documents %}
              <tr>
                <th scope="row">{{ doc.name }}</th>
                <td>
                  <a href="{{ doc.file.url }}" target="_blank">Просмотреть</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="container">
    {% include 'main/player_id/edit_delete_buttons.html' %}
  </div>
{% endblock content %}

adaptive_hockey_federation/templates/main/player_id/player_id_create_edit.html
{% extends 'base/base.html' %}
{% load static %}
{% load user_filters %}
{% block title %}
    {{ page_title }}
{% endblock %}

{% block content %}
<h2 class="text-center mb-4">{{ page_title }}</h2>
<form id="playerForm" method="post" enctype="multipart/form-data" data-discipline-level="{% url 'main:ajax_load_discipline_levels' %}">
    {% csrf_token %}
    <div class="container text-center">
        <div class="full-container">
            <h4 class="text-center mb-4">Личная информация</h4>
            <table class="table-table">
                <tbody>
                  {% for field in form.visible_fields %}
                    {% if field.name in 'surname name patronymic birthday identity_document '%} {% include "main/fields/text_input_field.html" %}
                      {% elif  field.name in 'gender discipline_name discipline_level nosology' %} {% include "main/fields/select_field.html" %}
                      {% elif  field.name in 'diagnosis' %} {% include "main/fields/diagnosis_field.html" %}
                    {% endif %}
                  {% endfor %}
                </tbody>
              </table>
        </div>
        <div class="full-container">
            <h4 class="text-center mb-4">Игровая информация</h4>
            <table class="table-table">
              <tbody>
                {% for field in form.visible_fields %}
                  {% if field.name in "level_revision number"%} {% include "main/fields/text_input_field.html" %}
                    {% elif  field.name in "team" %} {% include "main/fields/team_select_field_2_fields.html" %}
                    {% elif  field.name in "is_captain is_assistent" %} {% include "main/fields/check_box_field.html" %}
                    {% elif  field.name in "position" %} {% include "main/fields/select_field.html" %}
                  {% endif %}
                {% endfor %}
              </tbody>
            </table>
        </div>
        <h4 class="text-center mb-4">Документы</h4>
        {% if errormessage %}
            <h6 class="text-center mb-6" style="color:red">{{ errormessage }}</h6>
        {% endif %}
        <table class="table-table">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Файл</th>
                    <th>Удалить</th>
                </tr>
            </thead>
            <tbody id="fileUploadContainer">
            {% if player_documents %}
                {% for doc in player_documents %} {% include "main/fields/documents_field.html" %}{% endfor %}
            {% endif %}
            </tbody>
        </table>
        <button id="addFileButton" type="button" class="btn btn-primary">+</button>
        {% if team_id %}
          <input type="hidden" value="{{ team_id }}" name="team_id" >
        {% endif %}
        <!-- Save Button -->
        <div class="container">
            <div class="row">
                <div class="col text-center text-white flex justify-start">
                    <button
                    type="submit"
                    class="btn btn-secondary text-white"
                    style="background-color: #64C2D1; border: 1px solid #fff;"
                    >
                        Сохранить
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block JavaScript %}
<script>
let deleteButtons = document.querySelectorAll("#deleteFileButton");

function addDeleteButtonEvent(button) {
    button.addEventListener("click", function() {
        const parentRow = this.closest("tr");
        const a_tag = parentRow.querySelector("a");
        if (a_tag) {
            const fileName = a_tag.getAttribute("href");
            let hiddenInput = document.createElement("input");
            hiddenInput.style.display = "none";
            hiddenInput.name = "deleted_file_path[]";
            hiddenInput.value = fileName;
            parentRow.appendChild(hiddenInput);
        }
        parentRow.style.display = "none";
    });
}

function addNewFileField() {
    let fileUploadContainer = document.getElementById('fileUploadContainer');
    let newFileUpload = document.createElement("tr");
    newFileUpload.classList.add("file-upload-container");
    newFileUpload.classList.add("m-2");
    newFileUpload.innerHTML = `
            <td><input type="text" name="new_file_name[]" placeholder="Name" class="form-control"></td>
            <td><input type="file" name="new_file_path[]" accept="{{ file_resolution }}" class="form-control"></td>
        `;
    const deleteButton = document.createElement("button");
    deleteButton.id = "deleteFileButton";
    deleteButton.type = "button";
    deleteButton.className = "btn btn-danger";
    deleteButton.textContent = "-";
    addDeleteButtonEvent(deleteButton);

    const newTd = document.createElement("td");
    newTd.appendChild(deleteButton);
    newFileUpload.appendChild(newTd);
    fileUploadContainer.appendChild(newFileUpload);
}

deleteButtons.forEach(function(button) {
    addDeleteButtonEvent(button);
});

document.getElementById('addFileButton').addEventListener('click', function() {
    addNewFileField()
});

addNewFileField()
    const mover = new SelectManipulation('id_available_teams', 'id_team');
    const selectAllSelected = new SelectAllSelected('id_team');
    const search_available_teams = new SearchValue('id_available_teams', 'selector-filter-available');
    const search_current_teams = new SearchValue('id_team', 'selector-filter-current');
</script>
{% endblock %}

adaptive_hockey_federation/templates/main/player_id/player_id_deleted.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
  Карточка удалена
{% endblock %}

{% block content %}
  <h2 class="text-center mb-4">Карточка игрока успешно удалена</h2>
  <p class="text-center"><a href="{% url 'main:players' %}">Вернуться к списку игроков</a></p>
{% endblock %}

adaptive_hockey_federation/templates/main/player_id/player_id_video_games.html
{% extends 'base/base.html' %}
{% block title %}
  Видео игр
{% endblock %}
{% block content %}
  {% include 'base/messages.html' %}
  {% include 'main/games/table.html' with table_head=table_head table_data=table_data %}
{% endblock %}

adaptive_hockey_federation/templates/main/player_id/video_games_button.html
<div class="text-center">
    {% if has_video_games %}
    <div class="text-center">
        <div style="display: flex; justify-content: center;">
            <a href="{% url 'main:player_id_games_video' pk=player.pk %}" class="btn btn-secondary text-white" style="background-color: #64C2D1; border: 1px solid #fff; margin-right: 10px;">Видео игр с игроком</a>
        </div>
    </div>
    {% endif %}
</div>