adaptive_hockey_federation/adaptive_hockey_federation/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
]

adaptive_hockey_federation/analytics/urls.py
from analytics import views
from django.urls import include, path

app_name = "analytics"

analytics_urlpatterns = [
    path("", views.AnalyticsListView.as_view(), name="analytics"),
]

urlpatterns = [
    path("analytics/", include(analytics_urlpatterns)),
]

adaptive_hockey_federation/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("", include("users.urls", namespace="users")),
    path("", include("competitions.urls", namespace="competitions")),
    path("", include("analytics.urls", namespace="analytics")),
    path("", include("unloads.urls", namespace="unloads")),
    path("auth/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "core.views.not_found"
handler403 = "core.views.forbidden"
handler500 = "core.views.internal_server_error"

adaptive_hockey_federation/main/urls.py
from django.urls import include, path
from main.controllers import (
    ajax,
    main_views,
    player_views,
    staff_views,
    team_views,
)

app_name = "main"

main_urlpatterns = [
    path("", main_views.MainView.as_view(), name="main"),
]

players_urlpatterns = [
    path("", player_views.PlayersListView.as_view(), name="players"),
    path(
        "create/",
        player_views.PlayerIDCreateView.as_view(),
        name="player_create",
    ),
    path(
        "<int:pk>/",
        player_views.PlayerIdView.as_view(),
        name="player_id",
    ),
    path(
        "<int:pk>/edit/",
        player_views.PlayerIDEditView.as_view(),
        name="player_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        player_views.PlayerIDDeleteView.as_view(),
        name="player_id_delete",
    ),
    path(
        "deleted/",
        player_views.player_id_deleted,
        name="player_id_deleted",
    ),
]

teams_urlpatterns = [
    path("", team_views.TeamListView.as_view(), name="teams"),
    path(
        "create/",
        team_views.CreateTeamView.as_view(),
        name="team_create",
    ),
    path(
        "<int:team_id>/",
        team_views.TeamIdView.as_view(),
        name="teams_id",
    ),
    path(
        "<int:team_id>/edit/",
        team_views.UpdateTeamView.as_view(),
        name="team_update",
    ),
    path(
        "<int:team_id>/delete/",
        team_views.DeleteTeamView.as_view(),
        name="team_delete",
    ),
    path(
        "<int:team_id>/fire_staff/<int:staff_team_member_id>/",
        team_views.FireStaffFromTeam.as_view(),
        name="fire_staff_from_team",
    ),
]

staffs_urlpatterns = [
    path(
        "",
        staff_views.StaffMemberListView.as_view(),
        name="staffs",
    ),
    path(
        "create/",
        staff_views.StaffMemberIdCreateView.as_view(),
        name="staff_create",
    ),
    path(
        "<int:pk>/",
        staff_views.StaffMemberIdView.as_view(),
        name="staff_id",
    ),
    path(
        "<int:pk>/edit/",
        staff_views.StaffMemberIdEditView.as_view(),
        name="staff_id_edit",
    ),
    path(
        "<int:pk>/delete/",
        staff_views.StaffMemberIdDeleteView.as_view(),
        name="staff_id_delete",
    ),
    path(
        "<int:pk>/<slug:position>/team/create/",
        staff_views.StaffMemberIdTeamCreateView.as_view(),
        name="staff_id_team_create",
    ),
    path(
        "<int:pk>/<slug:position>/team/edit/",
        staff_views.StaffMemberIDTeamEditView.as_view(),
        name="staff_id_team_edit",
    ),
    path(
        "<int:pk>/<slug:position>/team/delete/",
        staff_views.StaffMemberIdTeamDeleteView.as_view(),
        name="staff_id_team_delete",
    ),
]

ajax_urlpatterns = [
    path(
        "load-discipline-levels/",
        ajax.load_discipline_levels,
        name="ajax_load_discipline_levels",
    ),
    path(
        "filter-discipline-search/",
        ajax.filter_discipline_search,
        name="ajax_filter_discipline_search",
    ),
]

urlpatterns = [
    path("", include(main_urlpatterns)),
    path("players/", include(players_urlpatterns)),
    path("teams/", include(teams_urlpatterns)),
    path("staffs/", include(staffs_urlpatterns)),
    path("ajax/", include(ajax_urlpatterns)),
]

adaptive_hockey_federation/unloads/urls.py
from django.urls import include, path
from unloads import views

app_name = "unloads"

unloads_urlpattern = [
    path("", views.UnloadListView.as_view(), name="unloads"),
    path(
        "<str:page_name>/",
        views.DataExportView.as_view(),
        name="data_unloads",
    ),
    path(
        "<int:pk>/delete",
        views.DeleteUnloadView.as_view(),
        name="delete_unload",
    ),
]

urlpatterns = [
    path("unloads/", include(unloads_urlpattern)),
]

adaptive_hockey_federation/users/urls.py
from django.urls import include, path
from users.views import (
    CreateUserView,
    DeleteUserView,
    PasswordSetView,
    UpdateUserView,
    UsersListView,
)

app_name = "users"

users_urlpatterns = [
    path(
        "",
        UsersListView.as_view(),
        name="users",
    ),
    path(
        "create/",
        CreateUserView.as_view(),
        name="user_create",
    ),
    path(
        "<int:pk>/edit/",
        UpdateUserView.as_view(),
        name="user_update",
    ),
    path(
        "<int:pk>/delete/",
        DeleteUserView.as_view(),
        name="user_delete",
    ),
    path(
        "set_password/<uidb64>/<token>/",
        PasswordSetView.as_view(),
        name="password_set",
    ),
]

urlpatterns = [
    path("users/", include(users_urlpatterns)),
]

adaptive_hockey_federation/templates/base/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}">
    <link rel="stylesheet" href="{% static 'css/select.css' %}">
    <link rel="icon" type="image/ico" href="{% static 'favicon.ico' %}">

    <title>
      {% block title %}
      Тут будет заголовок
      {% endblock %}
    </title>

    <style>
      .content {
        min-height: calc(100vh - 162px);
      }
    </style>
  </head>

  <body>
    <div class="container__fluid">
      {% include 'base/drawer.html' %}
      <div class="page">
        <header class="header">
          {% block header %}
          {% include 'base/header.html' %}
          {% endblock %}
        </header>
        <main class="main">
          <div class="table-container">
            {% block content_navigation %}
            {% endblock %}
            {% block content %}
            Основной текст
            {% endblock %}
          </div>
        </main>
        {% block footer %}{% include 'base/footer.html' %}{% endblock %}
      </div>
    </div>
    <!-- JS block -->
    <script src="{% static 'js/jquery-select2.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tailwindvss-3.4.1.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script src="{% static 'js/select.js' %}"></script>
    <script src="{% static 'js/date-picker.js' %}"></script>
    <script src="{% static 'js/options-picker.js' %}"></script>
    <script src="{% static 'js/discipline-picker.js' %}"></script>
    <script src="{% static 'js/search.js' %}"></script>
    <script>
      tailwind.config = {
        prefix: "tw-",
        corePlugins: {
          preflight: false,
        }
      }
      const triangle = document.getElementById('triangle')
      const sidebar = document.getElementById('container__fluid')
      let isRotated = false
      function toggle_visibility(visabiliti) {
        if (visabiliti) {
          return
        } else {
          if (isRotated) {
            triangle.style.transform = 'rotate(0deg)'
          } else {
            triangle.style.transform = 'rotate(180deg)'
          }
          isRotated = !isRotated
          sidebar.classList.toggle('aside-navbar_opened')
        }
      }
      window.onload = toggle_visibility(true)
    </script>
    {% block JavaScript %}
    {% endblock %}
    <!-- End JS block -->
  </body>
</html>

adaptive_hockey_federation/templates/base/button.html
{% with request.path  as current_url_name %}
  <a href="{{ url_name }}"
    class="nav-link border border-2 border-white p-2 mx-1 w-44 text-left
    {% if current_url_name  == url_name %}
      drawler-menu-active
    {% else %}
      drawler_menu
    {% endif %}">
      {{ name }}
  </a>
{% endwith %}

adaptive_hockey_federation/templates/base/button_list.html
<div class="dropdown">
    <button class="border border-2 border-white p-2 px-4 drawler_menu dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
        + Добавить
    </button>
    <ul class="dropdown-menu" style="background-color: #64C2D1" aria-labelledby="dropdownMenuButton1">
      <li><a class="dropdown-item drawler_menu" style="color: #fff" href="#">Игрок</a></li>
      <li><a class="dropdown-item drawler_menu" style="color: #fff" href="#">Тренер</a></li>
    </ul>
</div>

adaptive_hockey_federation/templates/base/cell_button.html
<a href="{{ url }}" class="btn btn-secondary text-white"
    style="background-color: #64C2D1; border: 1px solid #fff;"
    role="button">{{ name }}
</a>

adaptive_hockey_federation/templates/base/check_icon.html
<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none"><g stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" opacity=".2"><path d="M2 16C2 8.268 8.268 2 16 2s14 6.268 14 14-6.268 14-14 14S2 23.732 2 16Z"/>
  <path d="m9.778 16 4.666 4.667 7.778-7.778"/></g>
</svg>

adaptive_hockey_federation/templates/base/competition_button_create.html
{% url 'competitions:competition_add' as competition_create_url %}
{% include 'base/button_create.html' with button_url=competition_create_url name="Создать соревнование" current_url_name=request.path %}

adaptive_hockey_federation/templates/base/delete_icon.html
<svg class="delete-icon" xmlns="http://www.w3.org/2000/svg">
  <path fill="#00000033" d="M15 .307c-8.272 0-15 6.73-15 15s6.728 15 15 15 15-6.73 15-15-6.728-15-15-15Zm0 26.666c-6.432 0-11.667-5.233-11.667-11.666C3.333 8.873 8.568 3.64 15 3.64c6.432 0 11.667 5.233 11.667 11.667 0 6.433-5.235 11.666-11.667 11.666Zm1.178-11.666 4.41-4.41a.837.837 0 0 0 0-1.179.836.836 0 0 0-1.178 0L15 14.128l-4.41-4.411a.833.833 0 0 0-1.178 1.178l4.41 4.412-4.41 4.41a.834.834 0 1 0 1.178 1.18L15 16.485l4.41 4.41a.833.833 0 1 0 1.18-1.177l-4.412-4.411Z"/><path fill="#000" fill-opacity=".2" d="M15 .307c-8.272 0-15 6.73-15 15s6.728 15 15 15 15-6.73 15-15-6.728-15-15-15Zm0 26.666c-6.432 0-11.667-5.233-11.667-11.666C3.333 8.873 8.568 3.64 15 3.64c6.432 0 11.667 5.233 11.667 11.667 0 6.433-5.235 11.666-11.667 11.666Zm1.178-11.666 4.41-4.41a.837.837 0 0 0 0-1.179.836.836 0 0 0-1.178 0L15 14.128l-4.41-4.411a.833.833 0 0 0-1.178 1.178l4.41 4.412-4.41 4.41a.834.834 0 1 0 1.178 1.18L15 16.485l4.41 4.41a.833.833 0 1 0 1.18-1.177l-4.412-4.411Z"/>
</svg>

adaptive_hockey_federation/templates/base/drawer.html
{% if not request.user.is_moderator %}
  <aside id="container__fluid" class="aside-navbar">
    <div class="navbar-container">
      <ul class="navigate">
        <div class="py-5 logo-zone">
          <div class="col-auto flex justify-end">
            <span class="logo-img">
              <img src="https://paraicehockey.ru/wp-content/uploads/2022/02/FAH_q.png" width="100" height="100">
            </span>
          </div>
          <div class="col text-white flex justify-start">
            Мир хоккея<br>для особенных<br>детей
          </div>
        </div>
        {% if not request.user.is_agent %}
          <li class="nav-item py-2 list-group">
            {% url 'main:players' as url_name %}{% include "base/button.html" with name="Игроки" %}
          </li>
          <li class="nav-item py-2">
            {% url 'users:users' as url_name %}{% include "base/button.html" with name="Пользователи" %}
          </li>
        {% endif %}
        <li class="nav-item py-2">
          {% url 'main:teams' as url_name %}{% include "base/button.html" with name="Команды" %}
        </li>
        {% if not request.user.is_agent %}
          <li class="nav-item py-2">
            {% url 'main:staffs' as url_name %}{% include "base/button.html" with name="Персонал команд" %}
          </li>
        {% endif %}
        <li class="nav-item py-2">
          {% url 'competitions:competitions' as url_name %}{% include "base/button.html" with name="Соревнования" %}
        </li>
        {% if not request.user.is_agent %}
          <li class="nav-item py-2">
            {% url 'analytics:analytics' as url_name %}{% include "base/button.html" with name="Аналитика" %}
          </li>
        {% endif %}
        {% if request.user.is_admin %}
          <li class="nav-item py-2">
            {% url 'unloads:unloads' as url_name %}{% include "base/button.html" with name="Выгрузки" %}
          </li>
        {% endif %}
      </ul>
      <button
        onclick="toggle_visibility(false);"
        class="nav-button"
        type="button"
        aria-controls="staticBackdrop"
        aria-expanded="true"
      >
        {% include "base/triangle.html" %}
      </button>
    </div>
  </aside>
{% endif %}

adaptive_hockey_federation/templates/base/footer.html
<footer class="footer footer-class">
  <nav class="navbar-footer">
    <div style="width: 50px;"></div>
    {% if request.resolver_match.view_name == 'main:teams' %}
      {% include "base/pagination_teams.html" %}
    {% else %}
      {% include "base/pagination.html" %}
    {% endif %}
    <nav class="p-2">
      <ul class="nav nav-pills mb-0 mt-1">
        {% with request.resolver_match.view_name as view_name %}
          {% if view_name == 'users:users' and perms.users.add_user %}
            {% include "base/user_button_create!.html" with name="+ Пользователь" %}
          {% endif %}
          {% if view_name == 'main:teams' %}
            {% include "base/team_button_create.html" with name="+ Команда" %}
          {% endif %}
          {% if view_name == 'competitions:competitions' and perms.competitions.add_competition %}
            {% include "base/competition_button_create.html" %}
          {% endif %}
          {% if view_name == 'main:players' %}
            {% include "main/players/player_button_create.html" %}
          {% endif %}
          {% if view_name == 'main:staffs' and perms.main.add_staffmember %}
            {% include "main/staffs/staff_button_create.html" %}
          {% endif %}
          {% if view_name == 'main:teams_id' %}
            {% if request.user == team.curator or user.is_staff %}
              {% include "main/teams_id/button_create_team_member.html" with name="+ Добавить" %}
            {% endif %}
          {% endif %}
          {% if view_name == 'games:games' %}
            {% include "main/games/game_button_create.html" %}
          {% endif %}
          {% if view_name == 'main:players' %}
            {% url 'unloads:data_unloads' page_name='players' as player_unload_url %}
            {% include "base/button.html" with url_name=player_unload_url name="Выгрузить" %}
          {% elif view_name == 'analytics:analytics' %}
            {% url 'unloads:data_unloads' page_name='analytics' as analytics_unload_url %}
            {% include "base/button.html" with url_name=analytics_unload_url name="Выгрузить" %}
          {% elif view_name == 'main:teams' %}
            {% url 'unloads:data_unloads' page_name='teams' as team_unload_url %}
            {% include "base/button.html" with url_name=team_unload_url name="Выгрузить" %}
          {% elif view_name == 'competitions:competitions' %}
            {% url 'unloads:data_unloads' page_name='competitions' as competition_unload_url %}
            {% include "base/button.html" with url_name=competition_unload_url name="Выгрузить" %}
          {% elif view_name == 'users:users' %}
            {% url 'unloads:data_unloads' page_name='users' as user_unload_url %}
            {% include "base/button.html" with url_name=user_unload_url name="Выгрузить" %}
          {% endif %}
        {% endwith %}
        {% if request.resolver_match.url_name in show_return_button %}
          {% include "base/return_button.html" %}
        {% endif %}
      </ul>
    </nav>
  </nav>
</footer>

adaptive_hockey_federation/templates/base/pagination_teams.html
<nav aria-label="Page navigation" class="p-2">
  <ul class="pagination justify-content-center mb-0 mt-1">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link pg-list bi bi-chevron-double-left border-2" href="?page=1&name={{ request.GET.name }}&discipline={{ request.GET.discipline }}&city={{ request.GET.city }}" aria-label="First"></a>
      </li>
      <li class="page-item">
        <a class="page-link pg-list bi bi bi-chevron-left border-2" href="?page={{ page_obj.previous_page_number }}&name={{ request.GET.name }}&discipline={{ request.GET.discipline }}&city={{ request.GET.city }}" aria-label="Previous"></a>
      </li>
    {% endif %}

    {% for num in paginator.page_range %}
      {% if num >= page_obj.number|add:-2 and num <= page_obj.number|add:2 %}
        {% if page_obj.number == num %}
          <li class="page-item page-num page-num-selected page-link pg-list-active border-2">
            {{ num }}
          </li>
        {% else %}
          <li class="page-item page-num pg-list">
            <a class="page-link pg-list border-2"
              href="?page={{ num }}&name={{ request.GET.name }}&discipline={{ request.GET.discipline }}&city={{ request.GET.city }}"
            >{{ num }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link pg-list bi bi-chevron-right border-2" href="?page={{ page_obj.next_page_number }}&name={{ request.GET.name }}&discipline={{ request.GET.discipline }}&city={{ request.GET.city }}" aria-label="Next"></a>
      </li>
      <li class="page-item">
        <a class="page-link pg-list bi bi-chevron-double-right border-2" href="?page={{ paginator.num_pages }}&name={{ request.GET.name }}&discipline={{ request.GET.discipline }}&city={{ request.GET.city }}" aria-label="Last"></a>
      </li>
    {% endif %}
  </ul>
</nav>

adaptive_hockey_federation/templates/base/return_button.html
<button onclick="history.back();" class="nav-link border border-2 border-white p-2 mx-1 w-44 text-left drawler_menu">Назад</button>

adaptive_hockey_federation/templates/base/search_form.html
<form method="GET">
  <div class="group-input">
    <select id="search_column" class="form-select select-form" aria-label="Default select example" name="search_column">
      {% for key, column_name in table_head.items %}
        {% if column_name != 'Nr.' and column_name != 'Просмотр/Excel' and key != 'video_link' and key != 'second_team' %}
          {% if key == 'first_team' %}
            <option value="team" id="search_{{ key }}">
              Команда
            </option>
          {% else %}
            <option value="{{ key }}" id="search_{{ key }}">
              {{ column_name }}
            </option>
          {% endif %}
        {% endif %}
      {% endfor %}
    </select>
    <input
      type="search"
      id="search_form_input"
      class="form-control select-form"
      name="search"
      aria-label="search"
      placeholder="{% if request.resolver_match.url_name in "players" %}Игрок
      {% elif request.resolver_match.url_name == "users" %}Пользователь
      {% elif request.resolver_match.url_name == "teams" %}Команда
      {% elif request.resolver_match.url_name in "teams_id" %}Игрок
      {% elif request.resolver_match.url_name == "competitions" %}Соревнование
      {% elif request.resolver_match.url_name == "analytics" %}Аналитика
      {% elif request.resolver_match.url_name == "games" %}Игры
      {% elif request.resolver_match.url_name == "player_id_games_video" %}Видео игр
      {% else %}Выгрузка
      {% endif %}"
      style="border-top-left-radius: 0; border-bottom-left-radius: 0;"
    />
    <div
      id="date-picker" style="display: none; border-radius: 0;">
      <select name="year" class="form-select picker__select" id="date-picker-year"></select>
      <select name="month" class="form-select picker__select" id="date-picker-month"></select>
      <select name="day" class="form-select picker__select" id="date-picker-day"></select>
    </div>
    <select
      name="gender"
      style="display: none; border-radius: 0;"
      class="form-select"
      id="gender-picker-select"
    ></select>
    <select
      name="active"
      style="display: none; border-radius: 0;"
      class="form-select"
      id="active-picker-select"
    ></select>
    <select
      name="discipline_name"
      style="display: none; border-radius: 0;"
      class="form-select"
      id="discipline-name-picker-select"
    ></select>
    <button id="search_button" type="submit" class="btn bg-white search__button">
      <i class="bi bi-search"></i>
    </button>
  </div>
</form>

adaptive_hockey_federation/templates/base/team_button_create.html
{% if perms.main.add_team %}
  {% url 'main:team_create' as team_create_url %}
  {% include 'base/button_create.html' with button_url=team_create_url name="Создать команду" current_url_name=request.path %}
{% endif %}

adaptive_hockey_federation/templates/base/team_edit_delete_buttons!.html
{% include "base/base_edit_delete_buttons.html" with action_url="main:team_update" delete_url="main:team_delete" is_activated=perms.team.change_team delete_message='Вы точно хотите удалить команду ' %}